# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RHDDX Documentation Site
email: adamj@redhat.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the documentation site for the developers.redhat.com site.
baseurl: "" # the subpath of your site if applicable, e.g. /blog
url: "https://rhddx.netlify.com" # the base hostname & protocol for your site, e.g. https://example.com
logo_url: https://rhddx.netlify.com/assets/img/NewRHDFullLogo_white.svg
NODE_VERSION: 10.16.0
NPM_VERSION: 6.13.2

# Permalink format (/blog/ is ignored for pages)
permalink: /blog/:title

# Enable the Publish Mode
# The publish_mode option allows you to enable "Editorial Workflow" mode for
# more control over the content publishing phases. All unpublished entries will be
# arranged in a board according to their status, and they can be further reviewed and edited before going live.
publish_mode: editorial_workflow

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids:   false

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

sass:
  sass_dir:   _sass
  style:      :compressed
  load_paths:
    - node_modules

# Keep files in the _site directory
keep_files:
  - assets/img
  - assets/main.css
  - assets/rhdp.css
  - assets/prism
  - themes

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - package-lock.json
  - CHANGELOG.md
  - node_modules
  - _sass
  - styles
  - assets
